### ISSUE TITLE
Can you give me your hardware configuration (your choice of GPU) please?

### ISSUE THREAD

**Issue by dongsuperbo007** [zombak79/vasp#1]
I failed to try using it on Tesla K80 12GB Vram (Colab) or Rtx 3080 10GB Vram (local).
This is the message I received

ResourceExhaustedError:  OOM when allocating tensor with shape[2048,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node model/Sigmoid (defined at \AppData\Local\Temp/ipykernel_15900/282231186.py:140) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.
 [Op:__inference_train_function_8754]

Function call stack:
train_function

**Comment by huynhbaobk** [comment]
> 

You could try use colab Pro with more GPU's RAM. I had same problem with Rtx 2070

**Comment by zombak79** [comment]
Hi!

It`s nice to see that you are interested in my model and recommender systems in general. Sorry to respond so late, but there were Christmas holidays in Europe and before that, I had covid. 

I run all my models on RTX3090 with 24GB of GPU RAM, so it is definitely possible, that they won`t run on GPUs with smaller memory. But, if you want to run the model on a smaller GPU, you can try:

- use smaller batch size: by default batch size is 1024. On the last line of cell #3, you can change the batch size with `batch_size` argument

```python
dataset.split.generators(batch_size=128)
```

- then I suggest changing the size of hidden layers by changing `hidden` argument on the second line in cell #4:

```python
m = VASP(dataset.split, name="VASP_ML20_1")
m.create_model(latent=2048, hidden=2048, ease_items_sampling=0.33)
m.model.summary()
```

These two changes should be enough to run GPU with 10 GB of GPU RAM, when I set experimental_growth on I get:

```
$ nvidia-smi
Wed Jan  5 16:56:04 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 3090    Off  | 00000000:4C:00.0 Off |                  N/A |
| 44%   65C    P2   320W / 350W |   9163MiB / 24265MiB |     93%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A    105491      C   /home/vojta/tf/bin/python3       9161MiB |
+-----------------------------------------------------------------------------+
```

But I would expect the results to be slightly worse with these settings.

Have fun with the VASP and if you have any questions, please ask :)

Cheers,
Vojta V.

EDIT:

After 36 epochs of training with a learning rate of 0.00005, I got 5-fold evaluation results (last cell in the notebook):

```
TEST SET (MEAN)
5-fold mean NCDG@100 0.447
5-fold mean Recall@20 0.415
5-fold mean Recall@50 0.551
```

And with finetuning for another 4 epochs with a learning rate of 0.00001 I got:

```
TEST SET (MEAN)
5-fold mean NCDG@100 0.449
5-fold mean Recall@20 0.417
5-fold mean Recall@50 0.554
```

Which are even better results than in the paper - stronger hardware is not always an advantage as I see :)
